name: image_picker_ios
description: iOS implementation of the image_picker plugin.
repository: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 0.8.11+2

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      ios:
        dartPluginClass: ImagePickerIOS
        pluginClass: FLTImagePickerPlugin
      

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  image_picker_platform_interface:
    git:
      url: https://github.com/saravanakumar007/image_picker_platform_interface.git
      ref: main
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  pigeon: ^14.0.0

topics:
  - camera
  - image-picker
  - files
  - file-selection