name: img_picker_ios
description: iOS implementation of the img_picker plugin.
repository: https://github.com/saravanakumar007/image_picker_ios
issue_tracker: https://github.com/saravanakumar007/image_picker_ios/issues
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      ios:
        dartPluginClass: ImagePickerIOS
        pluginClass: FLTImagePickerPlugin
      

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  img_picker_platform_interface: ^2.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  pigeon: ^14.0.0

topics:
  - camera
  - image-picker
  - files
  - file-selection